---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: ShowNewEvent

enabled: true

stickinessProperty: email

defaultValue:
  - percentage: 50
    option: true
  - percentage: 50
    option: false

conditions: []
