---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: EnablePayments
flagType: boolean
description: newDescription
labels:

availableValues:
  - "false"
  - "true"

isPermanent: false
