---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: EnableReviews
flagType: boolean
description: Reviews are fun!
labels:

availableValues:
  - "false"
  - "true"

isPermanent: false
