---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: MaintenanceMode
flagType: boolean
description: brandNewDescription
labels:

availableValues:
  - "false"
  - "true"

isPermanent: false
